export interface ThemeVars {
  "theme-bg": string;
  "theme-text": string;
  "theme-card-bg": string;
  "theme-card-text": string;
  "theme-border": string;
  "theme-primary": string;
  "theme-primary-hover": string;
  "theme-accent": string;
  "theme-accent-light": string;
  "theme-muted": string;
  "theme-muted-text": string;
  "theme-input-bg": string;
  "theme-shadow": string;
}

export const themes: Record<string, { label: string; vars: ThemeVars }> = {
  default: {
    label: "Yellow (Neo)",
    vars: {
      "theme-bg": "#facc15",
      "theme-text": "#000000",
      "theme-card-bg": "#ffffff",
      "theme-card-text": "#000000",
      "theme-border": "#000000",
      "theme-primary": "#2563eb",
      "theme-primary-hover": "#1d4ed8",
      "theme-accent": "#facc15",
      "theme-accent-light": "#fef08a",
      "theme-muted": "#f3f4f6",
      "theme-muted-text": "#6b7280",
      "theme-input-bg": "#ffffff",
      "theme-shadow": "rgba(0, 0, 0, 1)",
    },
  },
  "minimal-white": {
    label: "Minimal White",
    vars: {
      "theme-bg": "#f8fafc",
      "theme-text": "#0f172a",
      "theme-card-bg": "#ffffff",
      "theme-card-text": "#0f172a",
      "theme-border": "#e2e8f0",
      "theme-primary": "#3b82f6",
      "theme-primary-hover": "#2563eb",
      "theme-accent": "#3b82f6",
      "theme-accent-light": "#eff6ff",
      "theme-muted": "#f1f5f9",
      "theme-muted-text": "#64748b",
      "theme-input-bg": "#ffffff",
      "theme-shadow": "rgba(0, 0, 0, 0.08)",
    },
  },
  dark: {
    label: "Dark Slate",
    vars: {
      "theme-bg": "#0f172a",
      "theme-text": "#e2e8f0",
      "theme-card-bg": "#1e293b",
      "theme-card-text": "#f1f5f9",
      "theme-border": "#334155",
      "theme-primary": "#38bdf8",
      "theme-primary-hover": "#7dd3fc",
      "theme-accent": "#38bdf8",
      "theme-accent-light": "#1e3a5f",
      "theme-muted": "#1e293b",
      "theme-muted-text": "#94a3b8",
      "theme-input-bg": "#0f172a",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  neon: {
    label: "Neon Cyber",
    vars: {
      "theme-bg": "#1a0533",
      "theme-text": "#e0e7ff",
      "theme-card-bg": "#2e1065",
      "theme-card-text": "#ede9fe",
      "theme-border": "#4c1d95",
      "theme-primary": "#8b5cf6",
      "theme-primary-hover": "#a78bfa",
      "theme-accent": "#8b5cf6",
      "theme-accent-light": "#2e1065",
      "theme-muted": "#2e1065",
      "theme-muted-text": "#c4b5fd",
      "theme-input-bg": "#1a0533",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  forest: {
    label: "Forest",
    vars: {
      "theme-bg": "#064e3b",
      "theme-text": "#d1fae5",
      "theme-card-bg": "#065f46",
      "theme-card-text": "#ecfdf5",
      "theme-border": "#047857",
      "theme-primary": "#22c55e",
      "theme-primary-hover": "#4ade80",
      "theme-accent": "#22c55e",
      "theme-accent-light": "#064e3b",
      "theme-muted": "#065f46",
      "theme-muted-text": "#a7f3d0",
      "theme-input-bg": "#064e3b",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  ocean: {
    label: "Ocean",
    vars: {
      "theme-bg": "#0c4a6e",
      "theme-text": "#e0f2fe",
      "theme-card-bg": "#075985",
      "theme-card-text": "#f0f9ff",
      "theme-border": "#0369a1",
      "theme-primary": "#0ea5e9",
      "theme-primary-hover": "#38bdf8",
      "theme-accent": "#0ea5e9",
      "theme-accent-light": "#0c4a6e",
      "theme-muted": "#075985",
      "theme-muted-text": "#bae6fd",
      "theme-input-bg": "#0c4a6e",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  sunset: {
    label: "Sunset Blaze",
    vars: {
      "theme-bg": "#7c2d12",
      "theme-text": "#ffedd5",
      "theme-card-bg": "#9a3412",
      "theme-card-text": "#fff7ed",
      "theme-border": "#c2410c",
      "theme-primary": "#f97316",
      "theme-primary-hover": "#fb923c",
      "theme-accent": "#f97316",
      "theme-accent-light": "#7c2d12",
      "theme-muted": "#9a3412",
      "theme-muted-text": "#fed7aa",
      "theme-input-bg": "#7c2d12",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  nord: {
    label: "Nord",
    vars: {
      "theme-bg": "#2e3440",
      "theme-text": "#d8dee9",
      "theme-card-bg": "#3b4252",
      "theme-card-text": "#eceff4",
      "theme-border": "#4c566a",
      "theme-primary": "#88c0d0",
      "theme-primary-hover": "#8fbcbb",
      "theme-accent": "#88c0d0",
      "theme-accent-light": "#3b4252",
      "theme-muted": "#3b4252",
      "theme-muted-text": "#d8dee9",
      "theme-input-bg": "#2e3440",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  dracula: {
    label: "Dracula",
    vars: {
      "theme-bg": "#282a36",
      "theme-text": "#f8f8f2",
      "theme-card-bg": "#44475a",
      "theme-card-text": "#f8f8f2",
      "theme-border": "#6272a4",
      "theme-primary": "#bd93f9",
      "theme-primary-hover": "#ff79c6",
      "theme-accent": "#bd93f9",
      "theme-accent-light": "#44475a",
      "theme-muted": "#44475a",
      "theme-muted-text": "#c8c8f0",
      "theme-input-bg": "#282a36",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  toxic: {
    label: "Acid Toxic",
    vars: {
      "theme-bg": "#14532d",
      "theme-text": "#dcfce7",
      "theme-card-bg": "#166534",
      "theme-card-text": "#f0fdf4",
      "theme-border": "#15803d",
      "theme-primary": "#22c55e",
      "theme-primary-hover": "#4ade80",
      "theme-accent": "#22c55e",
      "theme-accent-light": "#14532d",
      "theme-muted": "#166534",
      "theme-muted-text": "#bbf7d0",
      "theme-input-bg": "#14532d",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  royal: {
    label: "Royal Gold",
    vars: {
      "theme-bg": "#2e1065",
      "theme-text": "#fef9c3",
      "theme-card-bg": "#4c1d95",
      "theme-card-text": "#fef08a",
      "theme-border": "#6d28d9",
      "theme-primary": "#eab308",
      "theme-primary-hover": "#facc15",
      "theme-accent": "#eab308",
      "theme-accent-light": "#2e1065",
      "theme-muted": "#4c1d95",
      "theme-muted-text": "#e9d5ff",
      "theme-input-bg": "#2e1065",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  "cotton-candy": {
    label: "Cotton Candy",
    vars: {
      "theme-bg": "#fdf2f8",
      "theme-text": "#831843",
      "theme-card-bg": "#ffffff",
      "theme-card-text": "#831843",
      "theme-border": "#fbcfe8",
      "theme-primary": "#ec4899",
      "theme-primary-hover": "#f472b6",
      "theme-accent": "#ec4899",
      "theme-accent-light": "#fce7f3",
      "theme-muted": "#fdf2f8",
      "theme-muted-text": "#be185d",
      "theme-input-bg": "#ffffff",
      "theme-shadow": "rgba(0, 0, 0, 0.08)",
    },
  },
  cyberpunk: {
    label: "Cyberpunk 2077",
    vars: {
      "theme-bg": "#020617",
      "theme-text": "#e0f2fe",
      "theme-card-bg": "#0f172a",
      "theme-card-text": "#f0f9ff",
      "theme-border": "#1e293b",
      "theme-primary": "#06b6d4",
      "theme-primary-hover": "#22d3ee",
      "theme-accent": "#06b6d4",
      "theme-accent-light": "#0f172a",
      "theme-muted": "#0f172a",
      "theme-muted-text": "#7dd3fc",
      "theme-input-bg": "#020617",
      "theme-shadow": "rgba(0, 0, 0, 0.6)",
    },
  },
  crimson: {
    label: "Crimson",
    vars: {
      "theme-bg": "#450a0a",
      "theme-text": "#fee2e2",
      "theme-card-bg": "#7f1d1d",
      "theme-card-text": "#fef2f2",
      "theme-border": "#991b1b",
      "theme-primary": "#ef4444",
      "theme-primary-hover": "#f87171",
      "theme-accent": "#ef4444",
      "theme-accent-light": "#450a0a",
      "theme-muted": "#7f1d1d",
      "theme-muted-text": "#fecaca",
      "theme-input-bg": "#450a0a",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  teal: {
    label: "Teal",
    vars: {
      "theme-bg": "#0f766e",
      "theme-text": "#ccfbf1",
      "theme-card-bg": "#115e59",
      "theme-card-text": "#f0fdfa",
      "theme-border": "#0d9488",
      "theme-primary": "#14b8a6",
      "theme-primary-hover": "#2dd4bf",
      "theme-accent": "#14b8a6",
      "theme-accent-light": "#0f766e",
      "theme-muted": "#115e59",
      "theme-muted-text": "#99f6e4",
      "theme-input-bg": "#0f766e",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  amber: {
    label: "Amber",
    vars: {
      "theme-bg": "#451a03",
      "theme-text": "#fef3c7",
      "theme-card-bg": "#78350f",
      "theme-card-text": "#fffbeb",
      "theme-border": "#92400e",
      "theme-primary": "#f59e0b",
      "theme-primary-hover": "#fbbf24",
      "theme-accent": "#f59e0b",
      "theme-accent-light": "#451a03",
      "theme-muted": "#78350f",
      "theme-muted-text": "#fde68a",
      "theme-input-bg": "#451a03",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  rose: {
    label: "Rose",
    vars: {
      "theme-bg": "#4c0519",
      "theme-text": "#ffe4e6",
      "theme-card-bg": "#881337",
      "theme-card-text": "#fff1f2",
      "theme-border": "#9f1239",
      "theme-primary": "#f43f5e",
      "theme-primary-hover": "#fb7185",
      "theme-accent": "#f43f5e",
      "theme-accent-light": "#4c0519",
      "theme-muted": "#881337",
      "theme-muted-text": "#fecdd3",
      "theme-input-bg": "#4c0519",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  zinc: {
    label: "Zinc",
    vars: {
      "theme-bg": "#18181b",
      "theme-text": "#e4e4e7",
      "theme-card-bg": "#27272a",
      "theme-card-text": "#fafafa",
      "theme-border": "#3f3f46",
      "theme-primary": "#a1a1aa",
      "theme-primary-hover": "#d4d4d8",
      "theme-accent": "#a1a1aa",
      "theme-accent-light": "#27272a",
      "theme-muted": "#27272a",
      "theme-muted-text": "#a1a1aa",
      "theme-input-bg": "#18181b",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  lime: {
    label: "Lime",
    vars: {
      "theme-bg": "#1a2e05",
      "theme-text": "#ecfccb",
      "theme-card-bg": "#365314",
      "theme-card-text": "#f7fee7",
      "theme-border": "#4d7c0f",
      "theme-primary": "#84cc16",
      "theme-primary-hover": "#a3e635",
      "theme-accent": "#84cc16",
      "theme-accent-light": "#1a2e05",
      "theme-muted": "#365314",
      "theme-muted-text": "#d9f99d",
      "theme-input-bg": "#1a2e05",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  stone: {
    label: "Stone",
    vars: {
      "theme-bg": "#1c1917",
      "theme-text": "#e7e5e4",
      "theme-card-bg": "#292524",
      "theme-card-text": "#fafaf9",
      "theme-border": "#44403c",
      "theme-primary": "#a8a29e",
      "theme-primary-hover": "#d6d3d1",
      "theme-accent": "#a8a29e",
      "theme-accent-light": "#292524",
      "theme-muted": "#292524",
      "theme-muted-text": "#d6d3d1",
      "theme-input-bg": "#1c1917",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  indigo: {
    label: "Indigo",
    vars: {
      "theme-bg": "#1e1b4b",
      "theme-text": "#e0e7ff",
      "theme-card-bg": "#312e81",
      "theme-card-text": "#eef2ff",
      "theme-border": "#4338ca",
      "theme-primary": "#6366f1",
      "theme-primary-hover": "#818cf8",
      "theme-accent": "#6366f1",
      "theme-accent-light": "#1e1b4b",
      "theme-muted": "#312e81",
      "theme-muted-text": "#c7d2fe",
      "theme-input-bg": "#1e1b4b",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
  sky: {
    label: "Sky",
    vars: {
      "theme-bg": "#0369a1",
      "theme-text": "#e0f2fe",
      "theme-card-bg": "#075985",
      "theme-card-text": "#f0f9ff",
      "theme-border": "#0284c7",
      "theme-primary": "#38bdf8",
      "theme-primary-hover": "#7dd3fc",
      "theme-accent": "#38bdf8",
      "theme-accent-light": "#0369a1",
      "theme-muted": "#075985",
      "theme-muted-text": "#bae6fd",
      "theme-input-bg": "#0369a1",
      "theme-shadow": "rgba(0, 0, 0, 0.4)",
    },
  },
  emerald: {
    label: "Emerald",
    vars: {
      "theme-bg": "#022c22",
      "theme-text": "#d1fae5",
      "theme-card-bg": "#064e3b",
      "theme-card-text": "#ecfdf5",
      "theme-border": "#065f46",
      "theme-primary": "#10b981",
      "theme-primary-hover": "#34d399",
      "theme-accent": "#10b981",
      "theme-accent-light": "#022c22",
      "theme-muted": "#064e3b",
      "theme-muted-text": "#a7f3d0",
      "theme-input-bg": "#022c22",
      "theme-shadow": "rgba(0, 0, 0, 0.5)",
    },
  },
};

export function applyTheme(themeKey: string): void {
  const theme = themes[themeKey] ?? themes.default;
  const root = document.documentElement;
  (Object.entries(theme.vars) as [keyof ThemeVars, string][]).forEach(([key, value]) => {
    root.style.setProperty(`--${key}`, value);
  });
}
